# Generated by Django 3.2.19 on 2025-08-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.parroquia')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula:')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres:')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos:')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo Electrónico: ')),
                ('telefono', models.IntegerField(verbose_name='Teléfono Celular')),
                ('telefono2', models.IntegerField(verbose_name='Teléfono Local o Alternativo')),
                ('fecha_naci', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('lugar_naci', models.CharField(max_length=200, verbose_name='Lugar de Nacimiento:')),
                ('nacionalidad', models.CharField(choices=[('v', 'V'), ('e', 'E')], max_length=2, verbose_name='Nacionalidad:')),
                ('titularidad', models.CharField(choices=[('pregrado', 'Pregado'), ('postgrado', 'Postgrado'), ('maestria', ',Maestria'), ('doctorado', 'Doctorado')], max_length=20, verbose_name='Titularidad:')),
                ('idiomas', models.CharField(max_length=200, verbose_name='Idiomas que Domina:')),
                ('ocupacion', models.CharField(max_length=200, verbose_name='Ocupación Actual:')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección en Venezuela:')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario_egresados.estado')),
                ('municipio_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario_egresados.municipio')),
                ('parroquia_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario_egresados.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beca', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=20, verbose_name='Tipo de Beca:')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera Cursada:')),
                ('fecha_ing', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_egr', models.DateField(verbose_name='Fecha de Egreso/Graduación')),
                ('tipo_becario', models.CharField(choices=[('extran_venz', 'Extranjero en Venezuela'), ('venz_venz', 'Venezolano(a) en Venezuela'), ('venz_extran', 'Venezolano(a) en el Extranjero')], max_length=20, verbose_name='Tipo de Becario:')),
                ('becario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to='formulario_egresados.datospersonales')),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario_egresados.universidad')),
            ],
        ),
    ]
