# Generated by Django 5.2.4 on 2025-08-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0005_alter_datospersonales_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(unique=True, verbose_name='Cédula:'),
        ),
    ]
