# Generated by Django 5.2.4 on 2025-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0006_alter_datospersonales_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_naci',
            field=models.CharField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
