# Generated by Django 5.2.4 on 2025-08-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0007_alter_datospersonales_fecha_naci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_naci',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
